=== ValeryiaZhdanava/newRep/ParseCandy/candy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam.com/candy"
	xmlns:tns="http://www.epam.com/candy" elementFormDefault="qualified">
	<element name="candys">
		<complexType>
			<sequence>
				<element name="candy" type="tns:candy" minOccurs="5"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<complexType name="candy">
		<sequence>
			<element name="name" type="string" />
			<element name="energy" type="string" />
			<element name="production" type="string" />
			<element name="value" type="tns:Value" />
			<element name="ingredients" type="tns:Ingredient" />
		</sequence>
		<attribute name="Type" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="caramel"></enumeration>
					<enumeration value="toffee"></enumeration>
					<enumeration value="chocolate"></enumeration>
					<enumeration value="chocolate with stuffed"></enumeration>
				</restriction>
			</simpleType>
		</attribute>

	</complexType>
	<complexType name="Value">
		<sequence>
			<element name="proteins" type="positiveInteger" />
			<element name="fats" type="positiveInteger" />
			<element name="carbahydrates" type="positiveInteger" />
		</sequence>
	</complexType>
	<complexType name="Ingredient">
		<sequence>
			<element name="fructose" type="positiveInteger" />
			<element name="sugar" type="positiveInteger" />
			<element name="vanilin" type="positiveInteger" />
			<element name="water" type="positiveInteger" />
		</sequence>
		<attribute name="typeOfchocolate" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="blackChocolate"></enumeration>
					<enumeration value="whiteChocolate"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

</schema>

=== ValeryiaZhdanava/newRep/ParseCandy/Candynew.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:candys xmlns:tns="http://www.epam.com/candy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.epam.com/candy candy.xsd ">
  <tns:candy Type="toffee">
    <tns:name>TOFFEE</tns:name>
    <tns:energy>200kkal</tns:energy>
    <tns:production>"ROSHEN"</tns:production>
    <tns:value>
      <tns:proteins>1</tns:proteins>
      <tns:fats>1</tns:fats>
      <tns:carbahydrates>1</tns:carbahydrates>
    </tns:value>
    <tns:ingredients typeOfchocolate="blackChocolate">
      <tns:fructose>1</tns:fructose>
      <tns:sugar>1</tns:sugar>
      <tns:vanilin>1</tns:vanilin>
      <tns:water>1</tns:water>
    </tns:ingredients>
  </tns:candy>
  <tns:candy Type="chocolate">
    <tns:name>KOROVKA</tns:name>
    <tns:energy>230kkal</tns:energy>
    <tns:production>"IVCON"</tns:production>
    <tns:value>
      <tns:proteins>1</tns:proteins>
      <tns:fats>1</tns:fats>
      <tns:carbahydrates>1</tns:carbahydrates>
    </tns:value>
    <tns:ingredients typeOfchocolate="blackChocolate">
      <tns:fructose>1</tns:fructose>
      <tns:sugar>1</tns:sugar>
      <tns:vanilin>1</tns:vanilin>
      <tns:water>1</tns:water>
    </tns:ingredients>
  </tns:candy>
  <tns:candy Type="caramel">
    <tns:name>tns:name</tns:name>
    <tns:energy>1</tns:energy>
    <tns:production>"KOMYNARKA"</tns:production>
    <tns:value>
      <tns:proteins>1</tns:proteins>
      <tns:fats>1</tns:fats>
      <tns:carbahydrates>1</tns:carbahydrates>
    </tns:value>
    <tns:ingredients typeOfchocolate="blackChocolate">
      <tns:fructose>1</tns:fructose>
      <tns:sugar>1</tns:sugar>
      <tns:vanilin>1</tns:vanilin>
      <tns:water>1</tns:water>
    </tns:ingredients>
  </tns:candy>
  <tns:candy Type="caramel">
    <tns:name>CHUPS</tns:name>
    <tns:energy>1</tns:energy>
    <tns:production>"CHUPIK"</tns:production>
    <tns:value>
      <tns:proteins>1</tns:proteins>
      <tns:fats>1</tns:fats>
      <tns:carbahydrates>1</tns:carbahydrates>
    </tns:value>
    <tns:ingredients typeOfchocolate="blackChocolate">
      <tns:fructose>1</tns:fructose>
      <tns:sugar>1</tns:sugar>
      <tns:vanilin>1</tns:vanilin>
      <tns:water>1</tns:water>
    </tns:ingredients>
  </tns:candy>
  <tns:candy Type="chocolate with stuffed">
    <tns:name>FTOPPY</tns:name>
    <tns:energy>1</tns:energy>
    <tns:production>"FERRERO"</tns:production>
    <tns:value>
      <tns:proteins>1</tns:proteins>
      <tns:fats>1</tns:fats>
      <tns:carbahydrates>1</tns:carbahydrates>
    </tns:value>
    <tns:ingredients typeOfchocolate="blackChocolate">
      <tns:fructose>1</tns:fructose>
      <tns:sugar>1</tns:sugar>
      <tns:vanilin>1</tns:vanilin>
      <tns:water>1</tns:water>
    </tns:ingredients>
  </tns:candy>
</tns:candys>
